<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.6</version>
		<relativePath/>
	</parent>

	<groupId>com.learnings.validators</groupId>
	<artifactId>spec-driven-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>spec-driven-parent</name>
	<description>Parent Maven project for the Spec Driven Validation Framework</description>
	<url>https://github.com/neelsharma2004/spec-driven-validation-framework</url>
	<licenses>
		<license>
			<name>Proprietary</name>
		</license>
	</licenses>
	<scm>
		<connection>scm:git:https://github.com/neelsharma2004/spec-driven-validation-framework.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/neelsharma2004/spec-driven-validation-framework.git</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/neelsharma2004/spec-driven-validation-framework</url>
	</scm>

	<modules>
		<module>spec-driven-validator</module>
	</modules>

	<properties>
		<java.version>21</java.version>
	</properties>
</project>
